FROM node:20-alpine as build

WORKDIR /app

ADD ./app /app

RUN npm ci
RUN npm run build
RUN npm ci --omit dev

FROM node:20-alpine

COPY --from=build /app/build /app/build
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/package.json /app/package.json
COPY --from=build /app/package-lock.json /app/package-lock.json
WORKDIR /app

CMD [ "node", "build" ]